# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables: 
- group: AzureResourcesVariableGroup

trigger:
- none

stages:
- stage: Build
  jobs: 
  - job: Build

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: DeployAzureResources
  jobs: 
  - job: DeployAzureResources
    pool: 
      vmImage: 'windows-latest'
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'app-service-sqldb-dotnetcore-service-connection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            # Create a resource group
            az group create --location $LOCATION --name $RESOURCEGROUPNAME
            echo "Created resource group $RESOURCEGROUPNAME"

            # Required resource access
            cat > manifest.json << EOF
            [
                {
                    "resourceAppId": "00000003-0000-0000-c000-000000000000",
                    "resourceAccess": [
                      {
                            "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
                            "type": "Scope"
                        }
                    ]
                }
            ]
            EOF

            # Create App Service plan
            az appservice plan create -g $RESOURCEGROUPNAME -n $SVCPLANNAME --sku FREE
            echo "Created App Service plan"

            ### Create Dev resources
            # create and configure Azure SQL logical server and Azure SQL database
            az sql server create -l $LOCATION -g $RESOURCEGROUPNAME -n $SQLSERVERNAMEDEV -u $ADMINUSER -p $ADMINPWD
            az sql db create -g $RESOURCEGROUPNAME -s $SQLSERVERNAMEDEV -n $DBNAME --service-objective Basic
            az sql server firewall-rule create -g $RESOURCEGROUPNAME -s $SQLSERVERNAMEDEV -n allowazure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
            echo "Created SQL server and SQL DB and SQL server firewall"

            # create and configure an Azure App web app
            az webapp create -g $RESOURCEGROUPNAME -p $SVCPLANNAME -n $WEBAPPNAMEDEV
            echo "Created App Service plan and webapp"

            ### Create Test resources
            # create and configure Azure SQL logical server and Azure SQL database
            az sql server create -l $LOCATION -g $RESOURCEGROUPNAME -n $SQLSERVERNAMETEST -u $ADMINUSER -p $ADMINPWD
            az sql db create -g $RESOURCEGROUPNAME -s $SQLSERVERNAMETEST -n $DBNAME --service-objective Basic
            az sql server firewall-rule create -g $RESOURCEGROUPNAME -s $SQLSERVERNAMETEST -n allowazure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
            echo "Created SQL server and SQL DB and SQL server firewall"

            # create and configure an Azure App Service web app
            az webapp create -g $RESOURCEGROUPNAME -p $SVCPLANNAME -n $WEBAPPNAMETEST
            echo "Created App Service webapp"

            redirectUriTest="https://$WEBAPPNAMETEST.azurewebsites.net/.auth/login/aad/callback"
            homePageUrlTest="https://$WEBAPPNAMETEST.azurewebsites.net"

            # Create app registration
            appIdTest=$(az ad app create --display-name $WEBAPPNAMETEST --query appId --output tsv)
            echo "Registered app: $appIdTest"

            # Get secret from the app for App Service authentication
            secretTest=$(az ad app credential reset --id $appIdTest --query password --output tsv)
            echo "Got secret"

            az config set extension.use_dynamic_install=yes_without_prompt
            az extension add --name authV2

            # Set identifier URI, homepage, redirect URI, and resource access
            az ad app update --id $appIdTest --identifier-urisTest api://$appIdTest --reply-urls $redirectUriTest  --homepage $homePageUrlTest --required-resource-accesses @manifest.json
            echo "Updated app"

            issuerTest="https://sts.windows.net/$TENANTID/"

            az webapp config appsettings set --name $WEBAPPNAMETEST --resource-group $RESOURCEGROUPNAME --slot-settings MICROSOFT_PROVIDER_AUTHENTICATION_SECRET=$secretTest
            echo "Set web app settings"

            az webapp auth microsoft update --name $WEBAPPNAMETEST --resource-group $RESOURCEGROUPNAME --client-id $appIdTest --secret-setting MICROSOFT_PROVIDER_AUTHENTICATION_SECRET --allowed-audiences $redirectUriTest  --issuer $issuerTest
            echo "Set EasyAuth settings"

            ### Create Staging resources
            # create and configure Azure SQL logical server and Azure SQL database
            az sql server create -l $LOCATION -g $RESOURCEGROUPNAME -n $SQLSERVERNAMESTAGING -u $ADMINUSER -p $ADMINPWD
            az sql db create -g $RESOURCEGROUPNAME -s $SQLSERVERNAMESTAGING -n $DBNAME --service-objective Basic
            az sql server firewall-rule create -g $RESOURCEGROUPNAME -s $SQLSERVERNAMESTAGING -n allowazure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
            echo "Created SQL server and SQL DB and SQL server firewall"

            # create and configure an Azure App Service web app
            az webapp create -g $RESOURCEGROUPNAME -p $SVCPLANNAME -n $WEBAPPNAMESTAGING
            echo "Created App Service webapp"

            redirectUriStaging="https://$WEBAPPNAMESTAGING.azurewebsites.net/.auth/login/aad/callback"
            homePageUrlStaging="https://$WEBAPPNAMESTAGING.azurewebsites.net"

            # Create app registration
            appIdStaging=$(az ad app create --display-name $WEBAPPNAMESTAGING --query appId --output tsv)
            echo "Registered app: $appIdStaging"

            # Get secret from the app
            secretStaging=$(az ad app credential reset --id $appIdStaging --query password --output tsv)
            echo "Got secret"

            az config set extension.use_dynamic_install=yes_without_prompt
            az extension add --name authV2

            # Set identifier URI, homepage, redirect URI, and resource access
            az ad app update --id $appIdStaging --identifier-urisStaging api://$appIdStaging --reply-urls $redirectUriStaging  --homepage $homePageUrlStaging --required-resource-accesses @manifest.json
            echo "Updated app"

            issuerStaging="https://sts.windows.net/$TENANTID/"

            az webapp config appsettings set --name $WEBAPPNAMESTAGING --resource-group $RESOURCEGROUPNAME --slot-settings MICROSOFT_PROVIDER_AUTHENTICATION_SECRET=$secretStaging
            echo "Set web app settings"

            az webapp auth microsoft update --name $WEBAPPNAMESTAGING --resource-group $RESOURCEGROUPNAME --client-id $appIdStaging --secret-setting MICROSOFT_PROVIDER_AUTHENTICATION_SECRET --allowed-audiences $redirectUriStaging  --issuer $issuerStaging
            echo "Set EasyAuth settings"
      
- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  condition: |
    and
    (
      succeeded()#,eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
    )
  jobs: 
  - job: Dev
    pool: 
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'app-service-sqldb-dotnetcore-service-connection'
        appType: 'webApp'
        WebAppName: '$(WEBAPPNAMEDEV)'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'         
    - task: AzureAppServiceSettings@1
      inputs:
        azureSubscription: 'app-service-sqldb-dotnetcore-service-connection'
        appName: '$(WEBAPPNAMEDEV)'
        resourceGroupName: '$(RESOURCEGROUPNAME)'
        connectionStrings: |
          [
            {
              "name": "MyDbConnection",
              "value": "Server=tcp:$(SQLSERVERNAMEDEV).database.windows.net,1433;Initial Catalog=tododb;Persist Security Info=False;User ID=$(ADMINUSER);Password=$(ADMINPWD);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;",
              "type": "SqlAzure",
              "slotSetting": false
            }
          ]
